# Generated by Django 4.2.11 on 2024-03-14 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_room_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_model',
            name='user_id',
        ),
    ]
